name: Update Issue Badge

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get number of open issues
        id: issues
        run: |
          ISSUES=$(curl -s "https://api.github.com/repos/${{ github.repository }}/issues?state=open&labels=bug" | jq length)
          echo "::set-output name=count::$ISSUES"

      - name: Set badge color
        id: badge
        run: |
          COUNT=${{ steps.issues.outputs.count }}
          if [ $COUNT -gt 10 ]; then
            COLOR="red"
          elif [ $COUNT -gt 5 ]; then
            COLOR="yellow"
          else
            COLOR="brightgreen"
          fi
          echo "::set-output name=color::$COLOR"

      - name: Update README
        run: |
          COLOR=${{ steps.badge.outputs.color }}
          sed -i "s|<img height=\"30px\" src=\"https://img.shields.io/github/issues/.*\" alt=\"Issues Badge\">|<img height=\"30px\" src=\"https://img.shields.io/github/issues/${{ github.repository }}?color=${COLOR}\" alt=\"Issues Badge\">|" README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update issue badge color"
          git push
